export const questions = {
  showQuestionNumbers: "off",
  pages: [
    {
      name: "page1",
      elements: [
       
            {
              type: "text",
              name: "email",
              title: "Please enter your e-mail",
              isRequired: true,
              validators: [
                {
                  type: "email",
                },
              ],
            },
            {
              type: "text",
              name: "name",
              title: "Inisial Nama",
            },
            {
              type: "dropdown",
              name: "domisili",
              title: "Provinsi",
              choices: [
                "ACEH",
                "SUMATERA UTARA",
                "SUMATERA BARAT",
                "RIAU",
                "JAMBI",
                "SUMATERA SELATAN",
                "BENGKULU",
                "LAMPUNG",
                "KEPULAUAN BANGKA BELITUNG",
                "KEPULAUAN RIAU",
                "DKI JAKARTA",
                "JAWA BARAT",
                "JAWA TENGAH",
                "DI YOGYAKARTA",
                "JAWA TIMUR",
                "BANTEN",
                "BALI",
                "NUSA TENGGARA BARAT",
                "NUSA TENGGARA TIMUR",
                "KALIMANTAN BARAT",
                "KALIMANTAN TENGAH",
                "KALIMANTAN SELATAN",
                "KALIMANTAN TIMUR",
                "KALIMANTAN UTARA",
                "SULAWESI UTARA",
                "SULAWESI TENGAH",
                "SULAWESI SELATAN",
                "SULAWESI TENGGARA",
                "GORONTALO",
                "SULAWESI BARAT",
                "MALUKU",
                "MALUKU UTARA",
                "PAPUA BARAT",
                "PAPUA",
              ],
            },
            {
              type: "radiogroup",
              name: "gender",
              title: "Jenis Kelamin",
              colCount: 3,

              choices: ["Laki-laki", "Perempuan", "Translaki", "Transpuan"],
              hasOther: true,
            },
            {
              type: "radiogroup",
              name: "umur",
              title: "Umur",
              colCount: 2,
              choices: ["18-25", "26-35", "36-45", "46-59", "60+"],
            },
          
      ],
    },
  ],
  completedHtml: "Terima kasih sudah mengisi PAKEM DIRI",
};
